### PR TITLE
Support for synchronous random bytes generation

### PR DESCRIPTION
**Pull request by arik-so**
Using Stanford's JavaScript Cryptography Library (SJCL), we have a seedable synchronous PRNG. We asynchronously initialize SJCL with a seed generated from the CSPRNG, and thus consistently support secure random number generation afterwards.

Additionally, if somebody has their own SJCL library, the module supports seeding any external SJCL instance using its newly exported seedSJCL method.

### CODE REVIEW

**Comment by mvayngrib** [comment]
@arik-so very cool, thanks for the PR! Can you explain the babelify script a bit? React native's packager already transpiles with babel

**Comment by mvayngrib** [comment]
you can also seed it synchronously by using [constantsToExport](https://facebook.github.io/react-native/docs/native-modules-ios.html#exporting-constants) and generating entropy iOS side

**Comment by arik-so** [comment]
Absolutely. The SJCL dependency doesn't work in the raw with react due to apparent reliance on Node core modules, which is why it has to be browserified. Browserify redefines the require method, however, in React 17, at least on iOS, overwriting require doesn't appear to be working. It's presumably a bug with their packager that they'll fix in 18, but given that it's a function defined on the fly anyway, it can be renamed to literally anything else that doesn't conflict, so I chose bitgoReq.

ConstantsToExport sounds like a great idea for synchronous seeding! Thank you for providing the library; we're not working on also adding the Android component using SecureRandom.

**Comment by mvayngrib** [comment]
i see, that makes sense. However, if other modules have similar dependencies on node core modules, you'll end up bundling all the shims multiple times. In that sense, it's better for the shimming to be done in a project itself, at the top, rather than in any one dependency. I would happily merge this solution minus the require substitution trick and shimming :)

**Comment by arik-so** [comment]
You are right. We're almost done with the Android inclusion though, and then will try to find a way around the dependency shimming.

**Comment by trave7er** [comment]
@arik-so

**Comment by trave7er** [comment]
@mvayngrib thanks for your pointer to `ConstantsToExport`. 

Question: if we are to generate the seed as a constant, do we still want to export the async version of native function? can we just create a seedable prng javascript side, and always use the "constant" seed?

**Comment by mvayngrib** [comment]
@trave7er can you point me to some documentation on the comparative security of the two, seeded prng vs SecCopyRandomBytes (which is also prng from /dev/random right?). Also, I'm a little concerned that with the synchronous version, we're keeping the seed in memory for the entire lifecycle of the app. I don't know if that's a big issue, I'm not an expert in this area. Is there a reason you want to remove the async version?

**Comment by trave7er** [comment]
@mvayngrib no reason at all. `/dev/random` will definitely be more preferable. Would you see the following two as similar situations: storing the seed as a constant in memory, and retrieving/storing a key in memory from keychain during life cycle? @arik-so @mvayngrib

**Comment by mvayngrib** [comment]
@trave7er i don't think the keychain can help in this case. If you store the seed there, you're back to async mode and you might as well use SecCopyRandomBytes.

**Comment by arik-so** [comment]
According to the definition of a CSPRNG (https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator#Requirements), even if the seed is known, it shouldn't pose a threat. However, it would certainly be preferable to have the ability to remove the value of the constant, though then it wouldn't be a constant any more.

**Comment by trave7er** [comment]
hi @mvayngrib, If you see any commit in this PR that you would like to cherry-pick, feel free to do so. Sorry for the delay and any confusion.

**Comment by mvayngrib** [comment]
@trave7er will try to do this weekend. I can merge and add a revert for some of the require magic and babelify. @arik-so maybe you want to rebase and squash some of the commits?

**Comment by mvayngrib** [comment]
@trave7er @arik-so merged, thanks guys! I removed the babelification from package.json. Take a look at [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) if you need a way to shim node core modules in react-native from the top down. It lacks documentation somewhat, but it works

**Comment by mvayngrib** [comment]
released as 2.0.0

**Pull request merged**
