### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by liuzhen2008**
I maybe crazy but i think this is the more correct documentation.

I don't see a "app" subdirectory anywhere.

### CODE REVIEW

**Comment by mvayngrib** [comment]
@liuzhen2008 thanks for pointing this out. Actually, i think we should scrap that whole section for manual install and tell people to just use `react-native link`. If you agree, could you update the PR?

**Comment by liuzhen2008** [comment]
@mvayngrib  I use windows to develop react-native applications. `react-native link `is not enough.

**Comment by mvayngrib** [comment]
@liuzhen2008 oh, interesting, didn't know that.

**Comment by mvayngrib** [comment]
@liuzhen2008 oh, interesting, didn't know that.

**Pull request merged**
