### PR TITLE
Support TVOS target

### PR DESCRIPTION
**Pull request by Max2817**
A specific TVOS target has been added to the library.

### CODE REVIEW

**Comment by mvayngrib** [comment]
@Max2817 thanks for the PR! However, I tried it out both with and without this PR, and it seems to work fine on the tvOS simulator regardless, so I'm curious if this is necessary. Am I missing something?

**Comment by Max2817** [comment]
I've followed the steps described in [Linking Libraries · React Native](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) to link the library to my tvOS target.  `react-native link` will not link the library with a tvOS target. I sent you a demo project to reproduce the error using weTransfer.

`RNRandomBytes.xcodeproj` only have support for iOS, so adding a target specifically for tvOS, `SUPPORTED_PLATFORMS = appletvsimulator appletvos`  we're able to link with a tvOS target.

**Comment by mvayngrib** [comment]
@Max2817 i've improved the README a bit. Your project works fine for me if I use the 2nd option in the Installation section (the one that doesn't require react-native-crypto):

```js
import { NativeModules } from 'react-native'
const { RNRandomBytes } = NativeModules
RNRandomBytes.randomBytes(32, (err, bytes) => {
  const message = err ? err.message : 'random: ' + bytes
  Alert.alert(message)
})
```

simulator screen shot - apple tv - 2018-04-19 at 12 33 21

**Comment by Max2817** [comment]
@mvayngrib can you share your working project? Because I can't manage to make it work properly on my side.

**Comment by Max2817** [comment]
@mvayngrib what version of Xcode are you on? because I still can't make the project compile.

**Comment by mvayngrib** [comment]
@Max2817 i'm on 9.3. What error are you seeing?

**Comment by Max2817** [comment]
@mvayngrib `no such file or directory: '/Users/nmartino/Library/Developer/Xcode/DerivedData/test_random_bytes-fsrcfwfanecgildqpsfvyotwbzti/Build/Products/Debug-appletvsimulator/libRNRandomBytes.a'`

**Comment by mvayngrib** [comment]
@Max2817 i see, and you get the same error with the project i linked? Have you tried wiping the relevant project dir in DerivedData and rebuilding?

**Comment by Max2817** [comment]
@mvayngrib Yes and I get the same error. And we get the same error on the colleague's computer too!

**Comment by mvayngrib** [comment]
@Max2817 no, sorry, didn't get around to it. But I tested on the simulator and iphone with your changes, and looked at a few other projects and they seem to have similar configuration changes to the ones you made. Merging :)

**Comment by mvayngrib** [comment]
released in 3.1.0

**Pull request merged**
