### PR TITLE
version fixes

### PR DESCRIPTION
**Pull request by mafaqriaz**
Here are some version fixes for android. Please update this package on npm. Thank you!

### CODE REVIEW

**Comment by mvayngrib** [comment]
@mafaqriaz could u explain why this is needed?

**Comment by mafaqriaz** [comment]
> @mafaqriaz could u explain why this is needed?

Actually, the npm package is not updated. When I install it in my project, it doesn't add the .podspecs file as well package.json file is also not up to date. Even .h and .m file in ios is not updated. Also for android, it gives an error (verifyReleaseResources) wile building. This is because of lower buildToolVersion and compiledSdkVersion. I had also written an email to you but you didn't replied me.

**Comment by mvayngrib** [comment]
@mafaqriaz ah, i thought this looked familiar 😁 

for Android, u can always overwrite the versions by adding a block in your project root android/build.gradle, e.g.:
```gradle
ext {
    buildToolsVersion = "29.0.2"
    compileSdkVersion = "30"
    ...
}
```

for iOS, ur right, it is missing the podspec, just republished as 3.6.1, thanks!

**Comment by mafaqriaz** [comment]
Yes, I know that but it's not in the case when you want to set up CI/CD pipelines on code magic or using some other platforms.

By the way, thanks for version 3.6.1. This will solve a lot of problems.

**Comment by mvayngrib** [comment]
> Yes, I know that but it's not in the case when you want to set up CI/CD pipelines on code magic or using some other platforms.

could u clarify why it's not the case?

**Comment by mafaqriaz** [comment]
We use codemagic in our organization to set up CI/CD pipeline along with bitbucket. And while pushing code on bitbucket node modules are added to the .gitignore file. While building the code on codemagic it re-installs all the modules using npm i command and we cannot change the version numbers during this building process.

**Comment by mvayngrib** [comment]
@mafaqriaz i see, but your `projectRoot/android/build.gradle` is not overwritten right? That's where you would put the above block (not in node_modules)

**Comment by mafaqriaz** [comment]
> @mafaqriaz i see, but your `projectRoot/android/build.gradle` is not overwritten right? That's where you would put the above block (not in node_modules)

No, Actually while building project if an npm package has lower buildToolVersion of compiledSdkVersion than projectRoot/android/build.gradle, then it raise error and breaks the building process.

**Comment by mvayngrib** [comment]
@mafaqriaz this package only falls back to specific values, it first checks your project root: https://github.com/mvayngrib/react-native-randombytes/blob/dccfcd84006921b230bd67c4d1e8f3dc6b03f2b0/android/build.gradle#L8-L9

**Comment by mafaqriaz** [comment]
Yes, I checked it now, it's updated in version 3.6.1. It was causing problem with the older version. I hope it will work now. Thank you for cooperating

**Pull request closed without merging**
